<?php

function scdhorizon_help($path, $arg) {
  switch ($path) {
    case "admin/help#scdhorizon":
      return '<p>' . t("Help text") . '</p>';
      break;
  }
} 

function scdhorizon_menu() {
  $items['user/%user/currentdocs'] = array(
        'title' => t('Documents en cours'),
        'page callback' => 'scdhorizon_currentdocs',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
  );  

  $items['quitus'] = array(
        'title' => t('Demander un quitus'),
        'page callback' => 'scdhorizon_quitus',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
  );  

  return $items;
}

function scdhorizon_quitus() {
  
  $candeliver = true;
  global $user;
  $userfields = user_load($user->uid);

  $out = "<h2>Vérifications:</h2>";

  if (array_key_exists('und', $userfields->field_horizon_uid))
  {
    $bn = $userfields->field_horizon_uid['und'][0]['value'];
    $out .= "<p class=\"text-success\"><span class=\"glyphicon glyphicon-ok\" aria-hidden=\"true\"></span> Identitiant trouvé dans le SIGB.</p>";
  }
  else
  {
    $out .= "<p class=\"text-danger\"><span class=\"glyphicon glyphicon-remove\" aria-hidden=\"true\"></span>Votre compte n'a pas pu être relié au SIGB.</p>";
    $candeliver = false;
  }

  if (isset($bn)) {
  
    global $databases;
    $H = $databases['horizon']['default'];
    $dbh = new PDO($H['driver'].":host=".$H['host'].":".$H['port'].";dbname=".$H['database'], $H['username'], $H['password']);
  
    $sth = $dbh->prepare("SELECT convert(varchar(10),dateadd(dd,last_cko_date, convert(date, '01/01/1970')),3),location,title,convert(varchar(10),dateadd(dd,due_date, convert(date, '01/01/1970')),3) FROM item_with_borrower WHERE borrower#=$bn");
  
    $sth->execute();
  
    $docs = $sth->fetchAll();
  
    if (! count($docs))
    {
      $out .= "<p class=\"text-success\"><span class=\"glyphicon glyphicon-ok\" aria-hidden=\"true\"></span> Aucun document en cours.</p>";
    }
    else
    {
      $out .= "<p class=\"text-danger\"><span class=\"glyphicon glyphicon-remove\" aria-hidden=\"true\"></span> Vous avez encore des documents en cours.</p>";
      $candeliver = false;
    }
  
    $sth = $dbh->prepare("select * from burb where borrower#=$bn and block in ('l','Note', 'suspend', 'od', 'notice1', 'notice2', 'notice3', 'notice4', 'rn', 'final', 'frais', 'quitus', 'refund', 'fee')");
  
    $sth->execute();
  
    $blockages = $sth->fetchAll();
  
    if (! count($blockages))
    {
      $out .= "<p class=\"text-success\"><span class=\"glyphicon glyphicon-ok\" aria-hidden=\"true\"></span> Aucun blocages.</p>";
    }
    else
    {
      $out .= "<p class=\"text-danger\"><span class=\"glyphicon glyphicon-remove\" aria-hidden=\"true\"></span> Votre compte fait l'objet d'un ou plusieurs blocages.</p>";
      $candeliver = false;
    }
  
    $dbh = null;
  }

  if ($candeliver) {
    $out .= "<button type=\"button\" class=\"btn btn-danger\">Cloturer votre compte et obtenir le quitus</button>";
  }
  else
  {
    $out .= "<p>Nous ne pouvons pas cloturer votre compte en l'état. Merci de prendre contact avec votre bibliothèque.</p>";
  }

  return $out;
}

function scdhorizon_cas_user_presave(&$edit, $account) {

  // borrower#

  $ldap_uid = $edit['field_ldap_uid']['und']['0']['value'];

  global $databases;
  $H = $databases['horizon']['default'];
  $dbh = new PDO($H['driver'].":host=".$H['host'].":".$H['port'].";dbname=".$H['database'], $H['username'], $H['password']);

  $sth = $dbh->prepare("SELECT * FROM borrower WHERE ville1='$ldap_uid'");
  $sth->execute();
  $huser = $sth->fetch();

  $edit['field_horizon_uid']['und'][0]['value'] = $huser['borrower#'];;

  // pole2

  $ldapattrs = cas_ldap_attributes($account->cas_name);

  $pole2 = 11;  
  if ($ldapattrs['pole2'][0] == "Guadeloupe")
    $pole2 = 10;
  $edit['field_ldap_pole2']['und'][0]['tid'] = $pole2;

  // affiliation

  $vocabulary = taxonomy_vocabulary_machine_name_load('Affiliation');
  $terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));

  $affiliation;
  foreach(explode(',', $ldapattrs['edupersonaffiliation'][0]) as $aff)
  {
    foreach($terms as $term)
    {
      if ($aff == $term->name)
        $edit['field_ldap_affiliation']['und'][0]['tid'] = $term->tid;
    }
  }

  // horizon_division

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'library')
    ->fieldCondition('field_id_bibliotheque', 'value', $huser['location'])
    ->propertyCondition('status', NODE_PUBLISHED);

  $result = $query->execute();

  foreach($result['node'] as $k => $v)
  {
    $edit['field_horizon_division']['und'][0]['nid'] = $k;
  }

  $dbh = null;
}

function scdhorizon_currentdocs($user) {
  if (! array_key_exists('und', $user->field_horizon_uid))
  {
    return "<p>Votre compte n'a pas pu être relié au SIGB.</p>";
  }

  $bn = $user->field_horizon_uid['und'][0]['value'];

  global $databases;
  $H = $databases['horizon']['default'];
  $dbh = new PDO($H['driver'].":host=".$H['host'].":".$H['port'].";dbname=".$H['database'], $H['username'], $H['password']);

  $sth = $dbh->prepare("SELECT convert(varchar(10),dateadd(dd,last_cko_date, convert(date, '01/01/1970')),3),location,title,convert(varchar(10),dateadd(dd,due_date, convert(date, '01/01/1970')),3) FROM item_with_borrower WHERE borrower#=$bn");

  $sth->execute();

  $docs = $sth->fetchAll();

  $dbh = null;

  if (! count($docs)) {
    return "<p>Aucun document en cours.</p>";
  }

  $out = "<table class=\"table table-striped\">";
  $out .= "<tr><th>Titre</th><th>Bibliothèque</th><th>Prêt le</th><th>Retour le</th></tr>";
  foreach ($docs as $doc) {
    $out .= "<tr>
               <td>".iconv('CP437', 'UTF-8', $doc['title'])."</td>
               <td>".$doc['location']."</td>
               <td>".$doc['computed']."</td>
               <td>".$doc['computed1']."</td>
             </tr>";
  }
  $out .= "</table>";

  return $out;
}

?>
